# Generated by Django 5.0.1 on 2024-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0002_remove_product_alanine_remove_product_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(),
        ),
    ]
