# Generated by Django 5.0.1 on 2024-02-19 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0003_alter_product_calories_alter_product_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Enter only alphabetical characters with or without commas.', regex='^[a-zA-Z,]+$')]),
        ),
    ]
