# Generated by Django 5.0.1 on 2024-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0005_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
    ]
