# Generated by Django 5.0.1 on 2024-03-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0007_usermodifiedproduct_alter_meal_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='meal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_carbohydrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='product',
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='carbohydrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='name',
            field=models.CharField(default='string'),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_modified_product', to='calculator_app.usermodifiedproduct'),
        ),
    ]
