# Generated by Django 5.0.1 on 2024-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0009_alter_meal_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='calories',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='carbohydrate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='fat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='name',
            field=models.CharField(blank=True, default='string'),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='protein',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
