# Generated by Django 5.0.1 on 2024-03-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0010_rename_product_meal_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='products',
        ),
        migrations.AddField(
            model_name='usermodifiedproduct',
            name='meal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='related_meal', to='calculator_app.meal'),
        ),
    ]
