# Generated by Django 5.0.1 on 2024-03-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0012_alter_usermodifiedproduct_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodifiedproduct',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_product', to='calculator_app.meal'),
        ),
    ]
