from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True, blank=False, null=False)
    serving_size = models.IntegerField(default=100, max_length=25, blank=False, null=False)
    calories = models.IntegerField(max_length=25)
    total_fat = models.DecimalField(max_digits=15, decimal_places=1)
    saturated_fat = models.DecimalField(max_digits=15, decimal_places=1)
    cholesterol = models.IntegerField(max_length=25)
    sodium = models.DecimalField(max_digits=15, decimal_places=2)
    choline = models.DecimalField(max_digits=15, decimal_places=1)
    folate = models.DecimalField(max_digits=15, decimal_places=2)
    folic_acid = models.DecimalField(max_digits=15, decimal_places=2)
    niacin = models.DecimalField(max_digits=15, decimal_places=3)
    pantothenic_acid = models.DecimalField(max_digits=15, decimal_places=3)
    riboflavin = models.DecimalField(max_digits=15, decimal_places=3)
    thiamin = models.DecimalField(max_digits=15, decimal_places=3)
    vitamin_a = models.DecimalField(max_digits=15, decimal_places=2)
    vitamin_a_rae = models.DecimalField(max_digits=15, decimal_places=2)
    carotene_alpha = models.DecimalField(max_digits=15, decimal_places=2)
    carotene_beta = models.DecimalField(max_digits=15, decimal_places=2)
    cryptoxanthin_beta = models.DecimalField(max_digits=15, decimal_places=2)
    lutein_zeaxanthin = models.DecimalField(max_digits=15, decimal_places=2)
    lucopene = models.IntegerField(max_length=25)
    vitamin_b12 = models.DecimalField(max_digits=15, decimal_places=2)
    vitamin_b6 = models.DecimalField(max_digits=15, decimal_places=3)
    vitamin_c = models.DecimalField(max_digits=15, decimal_places=1)
    vitamin_d = models.DecimalField(max_digits=15, decimal_places=2)
    vitamin_e = models.DecimalField(max_digits=15, decimal_places=2)
    tocopherol_alpha = models.DecimalField(max_digits=15, decimal_places=2)
    vitamin_k = models.DecimalField(max_digits=15, decimal_places=1)
    calcium = models.DecimalField(max_digits=15, decimal_places=2)
    copper = models.DecimalField(max_digits=15, decimal_places=3)
    iron = models.DecimalField(max_digits=15, decimal_places=2)
    magnesium = models.DecimalField(max_digits=15, decimal_places=2)
    manganese = models.DecimalField(max_digits=15, decimal_places=3)
    phosphorous = models.DecimalField(max_digits=15, decimal_places=2)
    potassium = models.DecimalField(max_digits=15, decimal_places=2)
    selenium = models.DecimalField(max_digits=15, decimal_places=1)
    zink = models.DecimalField(max_digits=15, decimal_places=2)
    protein = models.DecimalField(max_digits=15, decimal_places=2)
    alanine = models.DecimalField(max_digits=15, decimal_places=3)
    arginine = models.DecimalField(max_digits=15, decimal_places=3)
    aspartic_acid = models.DecimalField(max_digits=15, decimal_places=3)
    cystine = models.DecimalField(max_digits=15, decimal_places=3)
    glutamic_acid = models.DecimalField(max_digits=15, decimal_places=3)
    glycine = models.DecimalField(max_digits=15, decimal_places=3)
    histidine = models.DecimalField(max_digits=15, decimal_places=3)
    hydroxyproline = models.DecimalField(max_digits=15, decimal_places=3)
    isoleucine = models.DecimalField(max_digits=15, decimal_places=3)
    leucine = models.DecimalField(max_digits=15, decimal_places=3)
    lysine = models.DecimalField(max_digits=15, decimal_places=3)
    methionine = models.DecimalField(max_digits=15, decimal_places=3)
    phenylalanine = models.DecimalField(max_digits=15, decimal_places=3)
    proline = models.DecimalField(max_digits=15, decimal_places=3)
    serine = models.DecimalField(max_digits=15, decimal_places=3)
    threonine = models.DecimalField(max_digits=15, decimal_places=3)
    tryptophan = models.DecimalField(max_digits=15, decimal_places=3)
    tyrosine = models.DecimalField(max_digits=15, decimal_places=3)
    valine = models.DecimalField(max_digits=15, decimal_places=3)
    carbohydrate = models.DecimalField(max_digits=15, decimal_places=2)
    fiber = models.DecimalField(max_digits=15, decimal_places=1)
    sugars = models.DecimalField(max_digits=15, decimal_places=2)
    fructose = models.DecimalField(max_digits=15, decimal_places=2)
    galactose = models.DecimalField(max_digits=15, decimal_places=2)
    glucose = models.DecimalField(max_digits=15, decimal_places=2)
    lactose = models.DecimalField(max_digits=15, decimal_places=2)
    maltose = models.DecimalField(max_digits=15, decimal_places=2)
    sucrose = models.DecimalField(max_digits=15, decimal_places=2)
    fat = models.DecimalField(max_digits=15, decimal_places=2)
    saturated_fatty_acids = models.DecimalField(max_digits=15, decimal_places=3)
    monounsaturated_fatty_acids = models.DecimalField(max_digits=15, decimal_places=3)
    polyunsaturated_fatty_acids = models.DecimalField(max_digits=15, decimal_places=3)
    fatty_acids_total_trans = models.DecimalField(max_digits=15, decimal_places=2)
    alcohol = models.DecimalField(max_digits=15, decimal_places=1)
    ash = models.DecimalField(max_digits=15, decimal_places=2)
    caffeine = models.DecimalField(max_digits=15, decimal_places=2)
    theobromine = models.DecimalField(max_digits=15, decimal_places=2)
    water = models.DecimalField(max_digits=15, decimal_places=2)
